### PR TITLE
add src for plugin

### PR DESCRIPTION
**Pull request by JamesJeffryes**

### CODE REVIEW

**Comment by eapearson** [comment]
I've checked it out locally and it pulls up fine.
There are a few errors in the console log, which would be nice to clean up. You should be able to see them in the console (Chrome), log but for reference the top level error or warning message is below:

Warning: Encountered two children with the same key, `id`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

and 

./src/ReactionTable.js
  Line 11:  '_' is assigned a value but never used  no-unused-vars

**Comment by JamesJeffryes** [comment]
The first one is a known issue with the plugin I selected: https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/601 
It is however, a very minor one. I can banish it by duplicating the ID data but that seems wasteful. Let me know.

> ./src/ReactionTable.js
Line 11: '_' is assigned a value but never used no-unused-vars
the line that throws this is `const [_, stoic, cid] = /(\([0-9.]+\)) (\w+)/.exec(comp_txt);` I have to use this format because there's no way to just rab the last two values with javascript's destructuring assignment syntax. In Python `_` is commonly used for a variable that is syntactic only and not meant for use. I can switch to 
```
const match = /(\([0-9.]+\)) (\w+)/.exec(comp_txt);
const stoic = match[1];
const cid = match[2];
```
It just seems less elegant

**Comment by eapearson** [comment]
I feel your pain on this, and I have encountered this many times during development, but never with a library. Although in this case it may be minor, in general it is an important issue, and as the warning states, react's behavior around this may change in the future. Best to avoid undefined behavior!

I also understand running up against the differences between JS and Python destructuring. If you need to ignore the first element in an array destructuring, you can just omit the receiving variable altogether -- in other words just omit the underscore. `const [,b,c] = ['a', 'b', 'c']`

Although the replacement you suggest is indeed less elegant, it would still be preferable to generating a browser warning if need be (and prior to this last year was the only way to do it!)

And in reality, when doing regular expression matches, there is always the possibility of a match failure, in which case the destructuring will throw an error anyway. This really just implies that the regex match result should be checked, the null case handled, and in the success case the expected match positions pulled out. In Typescript (which we are probably using going forward for new projects), the type system will check this and require that kind of handling.

Generally I don't like to approve PRs that emit to the console for any reason other than errors and warnings issued intentionally and directly by our code. Their presence can make debugging in the browser more difficult, and of course they are visible to the curious user. 

Errors to console can be useful to provide better debugging support when replicating error conditions, but can be a sign that we've punted on error display. Warnings are rarely needed, but sometimes conditions detected may warrant it. For instance, in kbase-ui warnings are generated for a couple of libraries which use a dubious method of feature detection (which would throws an error, is caught, and then considered worthy of a warning), and for some data view specs which provide an icon but not a viewer widget (with the hope that one day these would be resolved.)

**Comment by eapearson** [comment]
Thanks, James. Looks great now. Do you want to to merge and release it, or have me do it? Doesn't matter to me.

**Comment by JamesJeffryes** [comment]
I can merge and tag it but I'm not sure what needs to be done to release
the kbase-ui

**Comment by eapearson** [comment]
you just need to create a release of the plugin (which also tags it), I'll make sure it is in the upcoming ui release.

**Comment by eapearson** [comment]
but it gets incorporated into the ui in ci pretty quickly.

**Pull request merged**
